# baseURL = "https://lachorale.ch"
title = "LACHORALE"
languageCode = "fr"
DefaultContentLanguage = "fr"
enableInlineShortcodes = true
theme = "nostyle"

[params]
custom_css = ["css/main.css"]
navTitle = "LA CHORALE ANARCHISTE"

description = "Depuis le printemps 2018, la chorale anarchiste chante un lundi sur deux à [l’espace autogéré](https://espaceautogere.squat.net) (rue César-Roux 30, Lausanne) et lors de divers événements et manifestations à Lausanne et ailleurs (plus d’info [ici](/flyers/201912_Article_Moins.jpg)). Il n’est pas trop tard pour nous rejoindre, bienvenue à tout le monde !"

favicon = "airbrush.png"
[params.meta]
favicon = true

[params.theme_config]
appearance = "light"
back_home_text = "ACCUEIL"
date_format = ""
show_description = true
